# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

In [ ]:
# HAW, Sarah Y.
# MEJORADA, Arabella Grace M.

## **Part 1**

In [9]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 1.2 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


#### 1. Import the numpy package under the name `np`


In [10]:
import numpy as np

#### 2. Print the numpy version

In [18]:
print(np.__version__)

2.0.2


#### 3. Create a null array of size 5

In [17]:
arr = np.array([0, 0, 0, 0, 0])
print(arr)

[0 0 0 0 0]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [16]:
arr = np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
print(arr)

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [21]:
fourbyfour_array = np.array([[[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]]])
print(fourbyfour_array)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]]]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [22]:
indices_array = np.array([1, 2, 4, 0, 4, 0])
x = np.where(indices_array != 0)

print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [27]:
ran_fourbyfour = np.random.randint(0, 20, [4, 4, 4])
ran_fourbyfour

array([[[12,  9, 16,  8],
        [ 8,  1, 17, 16],
        [11,  1, 16,  3],
        [ 2, 12, 10,  5]],

       [[ 1, 19,  2,  4],
        [10,  8, 12,  6],
        [ 8,  6, 17, 12],
        [ 1,  5,  9, 13]],

       [[18,  5, 14,  0],
        [ 3, 11, 16,  7],
        [ 7, 19,  1,  4],
        [10, 13, 13, 15]],

       [[ 5, 10,  3, 16],
        [18,  6,  7,  1],
        [16,  6, 15,  2],
        [16,  7,  3,  5]]])

#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [28]:
ran_fourbyfour.min()

np.int64(0)

In [29]:
ran_fourbyfour.max()

np.int64(19)

#### 9. Create a random array of size 25 and find the mean value

In [35]:
from numpy import random

x = random.randint(100, size=(25))
print(x)

[72 63 49  3 74 45 89 93 74 39 27 70  0 77 75 82  5 90 76 46 31 72 40 80
 36]


In [36]:
x.mean()

np.float64(56.32)

#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [38]:
arr_one = np.array([2, 4, 9])
arr_two = np.array([1, 14, 6])

print(arr_one)
print(arr_two)

[2 4 9]
[ 1 14  6]


10.1 What is the result of *a + b*?

In [39]:
print(np.add(arr_one, arr_two))

[ 3 18 15]


10.2 What is the result of *a - b*?

In [40]:
print(np.subtract(arr_one, arr_two))

[  1 -10   3]


10.3 What is the result of *a × b*?

In [41]:
print(np.multiply(arr_one, arr_two))

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [42]:
print(np.divide(arr_one, arr_two))

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [46]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [47]:
print(arr[1,1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [49]:
print(arr[1:2])

[[40 50 60]]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [50]:
print(arr[0:3, 2])


[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [58]:
arr = np.array([[50, 60], [80, 90]])

print(arr[0:2, 0:2])

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [60]:
slic_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(slic_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [61]:
sub_array = np.array([[6, 7], [10, 11]])
print(sub_array)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [79]:
newarr1 = slic_arr[0:1, 0]
newarr2 = slic_arr[0:1, 2]

concat = np.concatenate((newarr1, newarr2), axis=0)
print(concat)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [3]:
reverse_rows = slic_arr[::-1]
print(reverse_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [4]:
last_twocol = slic_arr[:, 2:4]
print(last_twocol)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [7]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print("arr1 =", arr1)
print("arr2 =", arr2)

arr1 = [11  7 33]
arr2 = [44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [8]:
joined_arr = np.concatenate((arr1, arr2))
print(joined_arr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [13]:
stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [14]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("arr1 =", arr1)
print("arr2 =", arr2)

arr1 = [[1 2]
 [3 4]]
arr2 = [[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [15]:
hjoin = np.hstack((arr1, arr2))
print(hjoin)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [17]:
vjoin = np.vstack((arr1, arr2))
print(vjoin)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.