# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

In [ ]:
# HAW, Sarah Y.
# MEJORADA, Arabella Grace M.

## **Part 1**

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


#### 1. Import the numpy package under the name `np`


In [12]:
import numpy as np

#### 2. Print the numpy version

In [18]:
print(np.__version__)

2.0.2


#### 3. Create a null array of size 5

In [17]:
arr = np.array([0, 0, 0, 0, 0])
print(arr)

[0 0 0 0 0]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [16]:
arr = np.array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])
print(arr)

[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [21]:
fourbyfour_array = np.array([[[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]]])
print(fourbyfour_array)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]]]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [22]:
indices_array = np.array([1, 2, 4, 0, 4, 0])
x = np.where(indices_array != 0)

print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [9]:
ran_fourbyfour = np.random.randint(0, 20, [4, 4, 4])
ran_fourbyfour

array([[[14, 18,  3, 14],
        [ 9, 19, 13, 19],
        [ 1,  5,  7, 15],
        [ 2,  9,  6,  5]],

       [[14, 12,  4, 12],
        [12,  1,  2, 18],
        [11,  7,  5,  7],
        [ 6, 18,  1,  6]],

       [[ 9,  0, 10, 16],
        [12,  3, 14,  3],
        [14, 13,  0,  2],
        [ 0,  9,  6, 11]],

       [[ 8,  9, 19,  7],
        [14, 12,  8,  2],
        [12,  9, 12,  9],
        [ 9, 19,  8, 17]]])

#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [10]:
ran_fourbyfour.min()

np.int64(0)

In [11]:
ran_fourbyfour.max()

np.int64(19)

#### 9. Create a random array of size 25 and find the mean value

In [7]:
from numpy import random

x = random.randint(100, size=(25))
print(x)

[75 55 49 15 94 75 57 54 80 39 49 19 74 52 26 35 34 85 73 38 55 55 63 74
  9]


In [36]:
x.mean()

np.float64(56.32)

#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [38]:
arr_one = np.array([2, 4, 9])
arr_two = np.array([1, 14, 6])

print(arr_one)
print(arr_two)

[2 4 9]
[ 1 14  6]


10.1 What is the result of *a + b*?

In [39]:
print(np.add(arr_one, arr_two))

[ 3 18 15]


10.2 What is the result of *a - b*?

In [40]:
print(np.subtract(arr_one, arr_two))

[  1 -10   3]


10.3 What is the result of *a × b*?

In [41]:
print(np.multiply(arr_one, arr_two))

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [42]:
print(np.divide(arr_one, arr_two))

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [13]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [14]:
print(arr[1,1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [15]:
print(arr[1:2])

[[40 50 60]]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [16]:
print(arr[0:3, 2])


[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [17]:
arr = np.array([[50, 60], [80, 90]])

print(arr[0:2, 0:2])

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [60]:
slic_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(slic_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [61]:
sub_array = np.array([[6, 7], [10, 11]])
print(sub_array)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [79]:
newarr1 = slic_arr[0:1, 0]
newarr2 = slic_arr[0:1, 2]

concat = np.concatenate((newarr1, newarr2), axis=0)
print(concat)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [3]:
reverse_rows = slic_arr[::-1]
print(reverse_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [4]:
last_twocol = slic_arr[:, 2:4]
print(last_twocol)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [7]:
arr1 = np.array([11, 7, 33])
arr2 = np.array([44, 5, 18])

print("arr1 =", arr1)
print("arr2 =", arr2)

arr1 = [11  7 33]
arr2 = [44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [8]:
joined_arr = np.concatenate((arr1, arr2))
print(joined_arr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [13]:
stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)

[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [14]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("arr1 =", arr1)
print("arr2 =", arr2)

arr1 = [[1 2]
 [3 4]]
arr2 = [[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [15]:
hjoin = np.hstack((arr1, arr2))
print(hjoin)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [17]:
vjoin = np.vstack((arr1, arr2))
print(vjoin)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [20]:
arr_1d = np.arange(10, 29, 2)
print("1D array:\n", arr_1d)

arr_2d = np.random.randint(1, 51, (4, 4))
print("2D array:\n", arr_2d)

arr_3d = np.ones((2, 3, 4), dtype=int)
print("3D array:\n", arr_3d)

1D array:
 [10 12 14 16 18 20 22 24 26 28]
2D array:
 [[16 14 30 33]
 [33 21 33 26]
 [44 10 15  3]
 [38 11  9 34]]
3D array:
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [ ]:
reshaped_arr = arr_1d.reshare(2, -1)
print("Reshaped 1D array:\n", reshaped_arr)

last_2_rows = arr_2d[-2:]
print("Last 2 rows of 2D array:\n", last_2_rows)

arr_2d[arr_2d % 2 == 0] = -1
print("2D array with even numbers replaced by -1:\n", arr_2d)

### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [34]:
arr_2d = np.random.randint(1, 51, (4, 4))

In [35]:
print(arr_2d.mean())

28.0


In [43]:
print(np.median(arr_2d))

28.0


In [42]:
print(np.std(arr_2d))

12.206555615733702


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [80]:
np.random.seed(42)
arr_10x10 = np.random.rand(10,10)
print(arr_10x10)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998 0.78517596
  0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
  0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802 0.54671028 0.18485446]
 [0.96958463 0.77513282 0.93949894 0.89482735 0.59789998 0.92187424
  0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
  0.14092422 0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212 0.81546143 0.70685734 0.72900717
  0.77127035 0.07404465 0.35846573 0.11586906]
 [0.86310343 0.62329813 0.33089802 0.06355835 0.31098232 0.32518332
  0.72960618

In [56]:
print(np.min(arr_10x10, axis=0))

[0.09430902 0.08608468 0.10522336 0.016145   0.00836429 0.06991848
 0.08756412 0.04684501 0.08949215 0.00215945]


In [86]:
print(np.unravel_index(np.argsort(arr_10x10, axis=None)[-5:], arr_10x10.shape))

(array([0, 3, 5, 1, 6]), array([1, 4, 0, 1, 9]))


In [88]:
flat_indx = np.argsort(arr_10x10.ravel())[-5:][::-1]
row_indx, col_indx = np.unravel_index(flat_indx, arr_10x10.shape)

for row, col in zip(row_indx, col_indx):
    print(f"[{row}, {Scol}]")

[6, 9]
[1, 1]
[5, 0]
[3, 4]
[0, 1]
